version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      production-dependencies:
        dependency-type: production
        update-types:
          - patch
    commit-message:
      prefix: chore(deps)
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      ci-actions:
        patterns:
          - '*'
    commit-message:
      prefix: chore(deps)
      include: scope
